# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [4]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [5]:
np.version.version

'1.16.6'

#### Q3 : Créer un vecteur nul de taille 10

In [3]:
import numpy as np
arr = np.empty(10)
print(arr)


[4.67589418e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 6.92046487e-310]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [19]:
arr = np.empty(10)
arr[5] = 1
print (arr[5])


[0 1 2 3 1 5 6 7 8 9]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [25]:
z = np.arange( 10, 51, 1 )

print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [26]:
z[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [30]:
c = np.arange(9).reshape(1,3,3); c

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### Q8 : Créer une matrice identié 3x3 

In [ ]:
c = np.arange(9).reshape(1,3,3); c

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [35]:
rd = np.random
rd.rand(3,3,3)

array([[[0.6090987 , 0.88096589, 0.02791358],
        [0.32652884, 0.27613104, 0.81670762],
        [0.93069904, 0.79126271, 0.66624606]],

       [[0.0815864 , 0.65523456, 0.90613262],
        [0.35488877, 0.71498807, 0.27727917],
        [0.34534598, 0.25373854, 0.05357343]],

       [[0.00240367, 0.13202469, 0.43148193],
        [0.63909862, 0.40610341, 0.65162127],
        [0.66845164, 0.7627866 , 0.92720405]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [36]:
rd = np.random
rd.rand(10,10)

array([[0.11998468, 0.2166787 , 0.64661371, 0.04247502, 0.74923405,
        0.50277866, 0.31489372, 0.81923134, 0.29677636, 0.02632773],
       [0.76428333, 0.90041858, 0.86597936, 0.64519699, 0.38779893,
        0.14695247, 0.87581872, 0.1447354 , 0.86498376, 0.98416925],
       [0.40790728, 0.12460349, 0.26147891, 0.85875459, 0.40697981,
        0.28875974, 0.44258324, 0.81460974, 0.16531861, 0.63163799],
       [0.32561007, 0.96293546, 0.88575521, 0.99980016, 0.81153348,
        0.02453993, 0.36365982, 0.20845267, 0.3704649 , 0.50366592],
       [0.1972071 , 0.73369013, 0.52356018, 0.28946825, 0.10552901,
        0.16958148, 0.44645135, 0.00247423, 0.60428791, 0.51470207],
       [0.27050433, 0.52068194, 0.36497081, 0.29577251, 0.15524732,
        0.0159324 , 0.52193586, 0.38609518, 0.24322375, 0.13786494],
       [0.44402213, 0.06747236, 0.57068703, 0.4772487 , 0.62433722,
        0.88161947, 0.98561611, 0.51779729, 0.80148513, 0.70051779],
       [0.35855263, 0.27345673, 0.6501400

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [34]:
neo = np.arange(1,5,1)
np.diag(neo,-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [57]:
arr1 = np.random.rand(5).cumsum()
print("Total de {} = {}".format(arr1, arr1.sum()))

Total de [0.60872819 1.31697256 1.65106792 1.9157446  2.86735942] = 8.35987269129


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [49]:
rd = np.random

rd.randint(0,5,5).mean()

1.8

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [58]:

l = [x for x in range(11)]
print(len(l))

11


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [61]:
rd = np.arange(0, 1, 0.1)
print(rd)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [62]:
A = np.array([0,1,2,3,4])
B = np.array([0,1,2,3,6])

if np.greater_equal(A, B).all():
    print("TRUE")
else :
    print("FALSE")

FALSE


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [64]:

a2_float = np.arange(0.0, 10.0, 1.5)
print("float : {}".format(a2_float))

a2_int = a2_float.astype(int)
print("int : {}".format(a2_int))


float : [0.  1.5 3.  4.5 6.  7.5 9. ]
int : [0 1 3 4 6 7 9]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [66]:
m = np.random.rand(5, 5)
print(m)

print("Moyenne matrice : {}".format(m.mean()))
print("Ecart type : {}".format(m.std()))
print( (m-m.mean())/m.std() )

[[0.89051014 0.47094477 0.30836273 0.36915494 0.52550279]
 [0.0512753  0.85527647 0.14966586 0.5418932  0.02634095]
 [0.33687647 0.88008643 0.19421581 0.82763209 0.5135958 ]
 [0.12012973 0.47624876 0.17785409 0.0661731  0.22073419]
 [0.06326433 0.19786246 0.73256015 0.60387912 0.46769068]]
Moyenne matrice : 0.402709214321
Ecart type : 0.274408979269
[[ 1.77764199  0.24866371 -0.34381705 -0.12227836  0.44748382]
 [-1.28069392  1.64924361 -0.9221395   0.50721369 -1.37155957]
 [-0.2399074   1.73965595 -0.75979075  1.54850209  0.40409242]
 [-1.02977493  0.26799249 -0.81941605 -1.22640342 -0.6631526 ]
 [-1.23700356 -0.74650164  1.20204132  0.73310249  0.23680517]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [ ]:

m2 = np.random.rand(3,3)
print(m2)

m2_transposed = m2.transpose()
print(m2_transposed)

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [67]:
import random

def randomCellReplacer(matrix):
    matrixLines  = np.size(matrix, 0)
    matrixColumn = np.size(matrix, 1)
    
    matrix[random.randint(0, matrixLines)-1, random.randint(0, matrixLines)-1] = 5555

m3 = np.random.rand(3,4)
print(m3)

randomCellReplacer(m3)
print(m3)

[[0.68796816 0.79979696 0.79383097 0.12863905]
 [0.53569507 0.57408467 0.5323795  0.15229332]
 [0.60350973 0.37919223 0.78984287 0.6740017 ]]
[[6.87968161e-01 7.99796957e-01 7.93830968e-01 1.28639050e-01]
 [5.35695067e-01 5.55500000e+03 5.32379503e-01 1.52293318e-01]
 [6.03509725e-01 3.79192234e-01 7.89842871e-01 6.74001702e-01]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [68]:

m4 = np.random.rand(5,5,3)
print(m4)

[[[0.0632628  0.46875961 0.51486441]
  [0.00678862 0.47607554 0.01837112]
  [0.57465544 0.05060821 0.58689579]
  [0.76199617 0.56132641 0.80588835]
  [0.1679017  0.77683308 0.61934187]]

 [[0.559885   0.3263454  0.06432442]
  [0.31003526 0.77986457 0.89784545]
  [0.05602602 0.31305528 0.19726403]
  [0.74194957 0.98119203 0.41920158]
  [0.8398466  0.99175313 0.49884713]]

 [[0.63742541 0.07666173 0.40965267]
  [0.97291791 0.7843422  0.71027874]
  [0.58437908 0.5781585  0.28036877]
  [0.58055333 0.4985075  0.59295131]
  [0.11401724 0.43114221 0.92122248]]

 [[0.29162912 0.98958069 0.82796495]
  [0.76205898 0.77083172 0.01206048]
  [0.19080188 0.00509534 0.07625174]
  [0.64804526 0.41034091 0.42807949]
  [0.95077114 0.31630581 0.52033138]]

 [[0.50988814 0.24614148 0.60679025]
  [0.82276396 0.14821264 0.12088226]
  [0.62995559 0.99192016 0.75442538]
  [0.04258925 0.84762038 0.41822968]
  [0.05636624 0.51527908 0.9907818 ]]]
