In [1]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

Donner le type de la variable rdm_mat

Donner la somme des éléments de ce tableau 2D

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [1]:
rdm_vect = np.random.randn(100)
rdm_vect.shape

(100,)

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

Afficher cette valeur 

Convertir le vecteur en un tableau 10, 10

array([[-2.99441404e-01,  1.78419461e+00,  1.62824730e+00,
         5.76998680e-01, -1.00798820e+00, -1.17629307e-01,
        -9.59793928e-01,  2.51709966e+00, -4.57689923e-01,
         5.64083233e-01],
       [ 1.08857553e+00,  1.25553582e+00,  1.41174036e+00,
         7.04405054e-01,  1.76417213e+00,  2.95989674e-01,
        -2.48375632e-01, -2.73836034e-01, -1.54983085e+00,
         6.81613252e-01],
       [-2.30990058e-04, -4.59307174e-01, -2.76918402e-01,
         1.39001379e-01, -3.43068545e-01,  1.38215348e+00,
         2.21448409e-01,  1.34330582e+00, -3.28983492e-01,
        -1.48319122e+00],
       [ 6.03851209e-02,  4.42199292e-01, -1.96886665e+00,
        -3.67291142e-01, -5.92191022e-01, -1.07593701e+00,
        -9.94270773e-01,  1.75063721e+00,  1.02451250e+00,
        -5.22313882e-03],
       [ 1.35937353e+00,  1.37572412e+00, -1.26344802e+00,
        -2.74771048e-01,  2.38997913e-01, -7.38658517e-01,
         1.31298051e+00,  1.60500160e-01,  1.03054547e-01,
         1.

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

array([-2.45928276e-01,  3.30057119e-01, -6.94069374e-02,  1.16367130e-02,
       -7.35080583e-02,  1.78359994e-04, -1.12472416e-01,  9.99337195e-01,
       -1.69671892e-01,  1.56672647e-01])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

array([ 4.22808072,  5.1299893 ,  0.19420926, -1.72604562,  3.31269044,
       -7.18438496,  1.73127593, -1.61666039,  1.17147191,  3.02831796])

Calculer la somme pour chaque ligne (sans boucles)

array([-2.45928276e+00,  3.30057119e+00, -6.94069374e-01,  1.16367130e-01,
       -7.35080583e-01,  1.78359994e-03, -1.12472416e+00,  9.99337195e+00,
       -1.69671892e+00,  1.56672647e+00])